version: '3.2'
services:
  emacs-mkdocs-export:
    image: emacs-mkdocs-export
    container_name: emacs-export
    volumes:
      - type: bind
        source: ~/Nextcloud/wiki/roam
        target: /roam
      - type: bind
        source: ./output
        target: /output
      - type: bind
        source: ./cache
        target: /cache
      - type: bind
        source: ./config
        target: /config
