name: Docker

on:
  push:
    branches: [ "main" ]
    # Publish server tags as releases.
    tags: [ 'v*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        id: tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            TAG_NAME=${{ github.ref }}
            TAG_NAME=${TAG_NAME##*/}
            echo "tag=$TAG_NAME" >> $GITHUB_ENV
            echo "latest_tag=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/main ]]; then
            echo "tag=main" >> $GITHUB_ENV
            echo "latest_tag=latest-unstable" >> $GITHUB_ENV
          fi

      - name: Convert repository name to lowercase
        id: lowercase-repo
        run: echo "lowercase_repo=$(echo '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.lowercase_repo }}:${{ env.tag }}
            ${{ env.lowercase_repo }}:${{ env.latest_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
